# Generated by Django 2.1.2 on 2020-04-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Director')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='GÃ©nero')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='PaÃ­s')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='TÃ­tulo')),
                ('tituloOriginal', models.TextField(verbose_name='TÃ­tulo Original')),
                ('fechaEstreno', models.DateField(verbose_name='Fecha de Estreno')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Director')),
                ('generos', models.ManyToManyField(to='main.Genero')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('ranking', models.TextField(verbose_name='Ranking actual')),
                ('autor',models.TextField(verbose_name='Autor del álbum')),
                ('semanas', models.TextField(verbose_name='Semanas en lista')),
                ('max_posicion', models.TextField(verbose_name='Máxima posición alcanzada')),
                ('discografica', models.TextField(verbose_name='Discográfica')),
                ('premios', models.TextField(verbose_name='Premios obtenidos')),
            ],
        ),
        
    ]
