# Generated by Django 3.1.3 on 2021-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('ranking', models.IntegerField(max_length=20, verbose_name='Ranking actual')),
                ('autor', models.TextField(verbose_name='Autor del álbum')),
                ('semanas', models.TextField(verbose_name='Semanas en lista')),
                ('max_posicion', models.TextField(verbose_name='Máxima posición alcanzada')),
                ('discografica', models.TextField(verbose_name='Discográfica')),
                ('premios', models.IntegerField(max_length=20, verbose_name='Premios obtenidos')),
            ],
        ),
    ]
