# Generated by Django 3.1.3 on 2021-01-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210114_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='premios',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Premios obtenidos'),
        ),
        migrations.AlterField(
            model_name='album',
            name='ranking',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Ranking actual'),
        ),
    ]
