# Generated by Django 3.1.3 on 2021-01-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210115_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(null=True, verbose_name='Autor')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='album',
            name='premios',
        ),
        migrations.AddField(
            model_name='album',
            name='premios',
            field=models.IntegerField(null=True, verbose_name='Premios'),
        ),
        migrations.DeleteModel(
            name='Premio',
        ),
        migrations.AddField(
            model_name='album',
            name='autor',
            field=models.ManyToManyField(to='main.Autor'),
        ),
    ]
