# Generated by Django 3.1.4 on 2021-01-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210115_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semanas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(null=True, verbose_name='Semanas')),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='album',
            name='semanas',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.AddField(
            model_name='album',
            name='semanas',
            field=models.ManyToManyField(to='main.Semanas'),
        ),
    ]
