# Generated by Django 3.1.3 on 2021-01-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210114_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='premios',
            field=models.TextField(max_length=20, verbose_name='Premios obtenidos'),
        ),
    ]
