# Generated by Django 3.1.3 on 2021-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210114_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='premios',
            field=models.IntegerField(max_length=20, verbose_name='Premios obtenidos'),
        ),
    ]
