# Generated by Django 3.1.3 on 2021-01-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210114_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True, verbose_name='Premio')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='premios',
        ),
        migrations.AddField(
            model_name='album',
            name='premios',
            field=models.ManyToManyField(to='main.Premio'),
        ),
    ]
