# Generated by Django 3.1.3 on 2021-01-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210115_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='premios',
            field=models.ManyToManyField(null=True, to='main.Premio'),
        ),
    ]
