# Generated by Django 3.1.3 on 2021-01-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210115_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='nombre',
            field=models.TextField(max_length=30, null=True, verbose_name='Premio'),
        ),
    ]
